### ISSUE TITLE
TypeError: elements is not iterable

### ISSUE THREAD

**Issue by gpugems** [localgod/catalyst#135]
> catalyst@1.0.0 exec
> node ./dist/catalyst.mjs -i diagram.puml -o output.drawio

file:///C:/Users/gpugems/Documents/GitHub/catalyst/dist/catalyst.mjs:11
    for (const element of elements) {
                          ^

TypeError: elements is not iterable
    at svg2mx (file:///C:/Users/gpugems/Documents/GitHub/catalyst/dist/catalyst.mjs:11:27)
    at Command.<anonymous> (file:///C:/Users/gpugems/Documents/GitHub/catalyst/dist/catalyst.mjs:73:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by localgod** [comment]
hi @gpugems 

To the best of my understanding this error occurs if Graphviz is not installed on your system (As require per the README). 

I have improved the error message in the `135-typeerror-elements-is-not-iterable` branch. Please verify Graphviz is installed and try again. 

I also found bug in the test diagram that has been fixed.
